// onlinejudge-admin/src/components/CompetitionInfo/ProblemSet.vue
<template>
  <el-table :data="tableData" style="width: 100%">
    <el-table-column prop="pid" label="#" width="180" />
    <el-table-column prop="title" label="标题" width="180" />
    <el-table-column prop="status" label="通过率">
      <template #default="scope">
        <el-tag type="success">
          {{isNaN(scope.row.acceptedCount/scope.row.tryCount)? '0.00%':(scope.row.acceptedCount/scope.row.tryCount * 100).toFixed(2) + '%'}}
        </el-tag>
      </template>
    </el-table-column>
    <el-table-column prop="level" label="难度">
      <template #default="scope">
        <el-tag effect="dark" type="success" v-if="scope.row.level === 0">简单</el-tag>
        <el-tag effect="dark" type="warning" v-else-if="scope.row.level === 1">普通</el-tag>
        <el-tag effect="dark" type="danger" v-else>困难</el-tag>
      </template>
    </el-table-column>
  </el-table>
</template>

<script setup lang="ts">
import {onMounted, ref, watch} from "vue";
import {getProblemInfoListByCid} from "../../axios/network/competition";

const props = defineProps({
  cid: {
    required: true,
    type: Number
  }
})
const tableData = ref([])
onMounted(() => {
  getProblemInfoListByCid(props.cid).then(res => {
    const {data} = res.data
    tableData.value = data
  })
})

watch(()=> props.cid,()=>{
  getProblemInfoListByCid(props.cid).then(res => {
    const {data} = res.data
    tableData.value = data
  })
})

</script>

<style scoped lang="scss">

</style>

// onlinejudge-react/src/pages/Competition/CompetitionInfo/ProblemSet/index.tsx
import {FC, ReactElement, useEffect, useState} from 'react';
import {Link, useLocation, useParams} from "react-router-dom";
import {getProblemListByCid} from "../../../../axios/network/competition";
import 'font-awesome/less/font-awesome.less';
import 'react-fontawesome';
import {Table, Tag} from "antd";
const { Column} = Table;

interface IProps{

}

const ProblemSet:FC<IProps> = (props):ReactElement => {
    const {id} = useParams()
    const [tableData,setTableData] = useState(new Array<any>())
    const pathname =  useLocation().pathname.replace('/problem-set','')
    useEffect(()=>{
        getProblemListByCid(id).then(res => {
            const {data} = res.data
            console.log(data)
            setTableData(data)
        })
    },[])
    return (
        <div>
            <Table dataSource={tableData} pagination={false}
                   rowKey={record => record.pid}
            >
                <Column width={"5%"} dataIndex="isAc" key="isAc" render={
                    (isAc)=> isAc !== -1 ? <i style={{color: "green"}} className={"fa fa-check"}/> : null
                } />
                <Column width={"8%"} title="#" dataIndex="pid" key="pid" />
                <Column width={"57%"} title="标题" dataIndex="title" key="title"
                        render={
                            (text,r:any)=>(
                                <Link to={pathname + "/p"+r.pid}>{text}</Link>
                            )
                        }
                />
                <Column width={"15%"} title="通过率" dataIndex="acRate" key="acRate" render={
                    (text,record:any)=>{
                        let acRate = record.acceptedCount/record.tryCount * 100
                        if (isNaN(acRate)) acRate = 0
                        return <>{acRate.toFixed(2) + '%'}</>
                    }
                }/>
                <Column width={"15%"} title="难度" dataIndex="level" key="level" render={
                    (level)=>{
                        if (level === 0){
                            return <Tag color="#87d068">简单</Tag>
                        }else if (level === 1){
                            return <Tag color="#F0AD4E">中等</Tag>
                        }else {
                            return <Tag color="#D9534F">困难</Tag>
                        }
                    }
                } />
            </Table>
        </div>
    );
};

export default ProblemSet;
