// onlinejudge-react/src/pages/Competition/CompetitionInfo/Description/index.tsx
import {FC, ReactElement, useEffect, useState} from 'react';
import {useParams} from "react-router-dom";
import {getCompetitionDesc} from "../../../../axios/network/competition";
import Editor from 'md-editor-rt';
import 'md-editor-rt/lib/style.css';
interface IProps{

}

const Description:FC<IProps> = (props):ReactElement => {
    const {id} = useParams()
    const [text,setText] = useState('')
    useEffect(()=>{
        getCompetitionDesc(id).then(res => {
            setText(res.data.data)
        })
    },[])
    return (
        <>
            <Editor
                modelValue={text}
                previewOnly
            />
        </>
    );
};

export default Description;

// onlinejudge-admin/src/components/CompetitionInfo/Description.vue
<template>
  <md-editor v-model="desc" previewOnly />
</template>

<script lang="ts" setup>
import MdEditor from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';
import {onMounted, ref, watch} from "vue";
import {getCompetitionDesc} from "../../axios/network/competition";

const props = defineProps({
  cid:{
    required:true
  }
})
const desc = ref('')

onMounted(() => {
  getCompetitionDesc(props.cid).then(res => {
    const {data} = res.data
    desc.value = data
  })
})
watch(()=>props.cid,()=>{
  getCompetitionDesc(props.cid).then(res => {
    const {data} = res.data
    desc.value = data
  })
})

</script>

<style scoped lang="scss">

</style>
